version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - JWT_SECRET=!secret jwt_secret 
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database_data:/var/lib/postgresql/data
secrets:
  jwt_secret:
    file: .jwt

volumes:
  database_data:
    driver: local
