# fly.toml app configuration file generated for conduit-nestjs on 2023-06-06T19:15:58-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "conduit-nestjs"
primary_region = "gru"

[http_service]
   
  internal_port = 8080 
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
